### PR TITLE
Change docker machine name to inviqa-dock-cli.

### PR DESCRIPTION
**Pull request by ThePixelDeveloper**
There's no references to Dinghy anywhere else so I assume this was leftover.
I've renamed it so you don't conflict with dinghy installations.

### CODE REVIEW

**Review by sroze — APPROVED** [review]
You are definitely right!

**Comment by ThePixelDeveloper** [comment]
Any update on this as it was approved?

**Comment by sroze** [comment]
Go on, let's merge it. Note that we know recommend Docker for Mac, to reduce the perceived complexity.

**Comment by ThePixelDeveloper** [comment]
Cheers!

**Pull request merged**
