### PR TITLE
Add additional networks for OSX, to support docker-compose v2's networking.

### PR DESCRIPTION
**Pull request by kierenevans**
172.17.0.0 isn't the only network created by docker-compose anymore.

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
If all the networks route to the same ip, you can just use a single network route that encompasses the whole range

**Comment by sroze** [comment]
Could you also update the [`DockerRouting.php` file](https://github.com/inviqa/dock-cli/blob/e73e2f858fc4bc1547a221428acf3679f37aaf8f/src/Installer/DNS/Mac/DockerRouting.php#L83) ?

**Review by sroze — CHANGES_REQUESTED** [review]
DockerRouting need to change as well

**Comment by kierenevans** [comment]
Updated!

**Comment by sroze** [comment]
Great, thanks Kieren 👍

**Pull request merged**
